-- 2025-02-11
SELECT C.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR AS C JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H
ON C.CAR_ID = H.CAR_ID
WHERE CAR_TYPE LIKE '세단' AND MONTH(start_date) >=10
GROUP BY C.CAR_ID
ORDER BY C.CAR_ID DESC
